Load the dataset

In [75]:
import pandas as pd
df = pd.read_csv("blood_type_distribution.csv")

Show the first 5 rows of the dataset.

In [76]:
df.head()

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent
0,Albania,3107100,34.10,31.20,14.5,5.20,6.00,5.50,2.60,0.90,EU
1,Algeria,47022473,40.00,30.00,15.0,4.25,6.60,2.30,1.10,0.75,AF
2,Argentina,46994384,50.34,31.09,8.2,2.16,4.29,2.98,0.74,0.20,SA
3,Armenia,2976765,29.00,46.30,12.0,5.60,2.00,3.70,1.00,0.40,AS
4,Australia,26768598,38.00,32.00,12.0,4.00,7.00,6.00,2.00,1.00,OC

Find the number of rows and columns in the dataset.

In [77]:
df.shape

(127, 11)

Find the column names in the dataset.

In [78]:
df.columns

Index(['Country', 'Population', 'O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-',
       'AB-', 'Continent'],
      dtype='str')

Check the data types and basic information of every column in the dataset.

In [79]:
df.dtypes

Country           str
Population      int64
O+            float64
A+            float64
B+            float64
AB+           float64
O-            float64
A-            float64
B-            float64
AB-           float64
Continent         str
dtype: object

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 127 entries, 0 to 126
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Country     127 non-null    str
 1   Population  127 non-null    int64
 2   O+          127 non-null    float64
 3   A+          127 non-null    float64
 4   B+          127 non-null    float64
 5   AB+         127 non-null    float64
 6   O-          126 non-null    float64
 7   A-          126 non-null    float64
 8   B-          126 non-null    float64
 9   AB-         124 non-null    float64
 10  Continent   116 non-null    str
dtypes: float64(8), int64(1), str(2)
memory usage: 12.3 KB

Check how many missing values there are in each column.

In [81]:
df.isnull().sum()

Country        0
Population     0
O+             0
A+             0
B+             0
AB+            0
O-             1
A-             1
B-             1
AB-            3
Continent     11
dtype: int64

Check whether your dataset contains any duplicate rows.

In [82]:
df.duplicated().sum()

np.int64(0)

Show the statistical summary of the numerical columns.

In [83]:
df.describe()

,Population,O+,A+,B+,AB+,O-,A-,B-,AB-
count,1.270000e+02,127.000000,127.000000,127.000000,127.000000,126.000000,126.000000,126.000000,124.000000
mean,1.226677e+08,40.424331,29.153622,16.287480,4.679921,4.126349,3.362619,1.360397,0.473710
std,7.324852e+08,9.874698,6.587261,7.510459,2.258816,2.669749,2.582812,0.867657,0.377158
min,4.027200e+04,27.000000,14.000000,4.720000,0.500000,0.060000,0.010000,0.010000,0.010000
25%,5.536691e+06,32.780000,24.130000,10.000000,2.850000,1.850000,1.000000,0.602500,0.130000
50%,1.301727e+07,38.000000,30.000000,15.000000,4.250000,4.295000,2.715000,1.300000,0.400000
75%,4.715145e+07,46.750000,34.000000,21.030000,6.300000,6.000000,6.000000,2.000000,0.900000
max,8.057236e+09,75.000000,46.300000,36.800000,11.320000,13.300000,9.000000,3.130000,1.200000

In [84]:
df['A-'].mean()

np.float64(3.362619047619048)

In [85]:
df['A-'] = df['A-'].fillna(df['A-'].mean())

In [86]:
df['B-'] = df['B-'].fillna(df['B-'].mean())

In [87]:
df['AB-'] = df['AB-'].fillna(df['AB-'].mean())

In [88]:
df['O-'] = df['O-'].fillna(df['O-'].mean())

In [89]:
df.isnull().sum()

Country        0
Population     0
O+             0
A+             0
B+             0
AB+            0
O-             0
A-             0
B-             0
AB-            0
Continent     11
dtype: int64

In [93]:
df['Continent'].mode()

0    AS
Name: Continent, dtype: str

In [97]:
df['Continent'] = df['Continent'].fillna(df['Continent'].mode()[0])

In [98]:
df.isnull().sum()

Country       0
Population    0
O+            0
A+            0
B+            0
AB+           0
O-            0
A-            0
B-            0
AB-           0
Continent     0
dtype: int64

In [99]:
df['Total_Positive'] = df['O+'] + df['A+'] + df['B+'] + df['AB+']

In [100]:
df['Total_Negative'] = df['O-'] + df['A-'] + df['B-'] + df['AB-']

In [102]:
df['Positive_Minus_Negative'] = df['Total_Positive'] - df['Total_Negative']

In [103]:
df[['Country', 'Total_Positive', 'Total_Negative', 'Positive_Minus_Negative']].head()

     Country  Total_Positive  Total_Negative  Positive_Minus_Negative
0    Albania           85.00           15.00                    70.00
1    Algeria           89.25           10.75                    78.50
2  Argentina           91.79            8.21                    83.58
3    Armenia           92.90            7.10                    85.80
4  Australia           86.00           16.00                    70.00

In [105]:
df.loc[df['Total_Positive'].idxmax(), 'Country']

'Nepal'

In [107]:
round(df['Total_Positive'].max(), 2)

np.float64(101.2)

In [108]:
df.loc[df['Total_Positive'].idxmin(), 'Country']

'World'

In [109]:
df.loc[df['Total_Negative'].idxmax(), 'Country']

'Mongolia'

In [110]:
df.loc[df['Total_Negative'].idxmin(), 'Country']

'Bhutan'

In [111]:
df['Total_Positive'].mean()

np.float64(90.54535433070866)

In [112]:
df['Total_Negative'].mean()

np.float64(9.323074756784434)

In [115]:
df.groupby('Continent')['Total_Positive'].mean().idxmax()

'AS'

In [116]:
df.groupby('Continent')['Total_Negative'].mean().idxmax()

'EU'

In [118]:
df[['O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-', 'AB-']].mean().idxmax()

'O+'

In [119]:
df[['O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-', 'AB-']].mean()

O+     40.424331
A+     29.153622
B+     16.287480
AB+     4.679921
O-      4.126349
A-      3.362619
B-      1.360397
AB-     0.473710
dtype: float64

In [124]:
df.groupby('Continent')['O+'].mean().idxmax()

'SA'

In [125]:
df.groupby('Continent')['A+'].mean().idxmax()

'EU'

In [126]:
pivot = df.pivot_table(
    index = 'Continent',
    values = ['O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-', 'AB-'],
    aggfunc = 'mean'
)
pivot

,A+,A-,AB+,AB-,B+,B-,O+,O-
Continent,,,,,,,,
AF,24.780435,1.799244,4.046087,0.350161,18.371304,1.159148,46.077391,3.477667
AS,27.577500,2.044808,5.585000,0.291225,20.527692,1.064423,39.866154,2.890577
EU,34.676410,6.203077,4.679487,0.862821,11.887179,2.076923,33.482564,6.007179
OC,32.375000,3.300000,3.475000,0.443427,12.025000,0.925000,43.675000,4.700000
SA,24.072222,2.691111,1.607778,0.171111,7.425556,0.673333,57.838889,4.518889

In [129]:
pivot['O+'].idxmax()

'SA'

In [134]:
high_pop_positive = df[(df['Population'] > 50000000) & (df['Total_Positive'] > 80)]

In [135]:
high_pop_positive

,Country,Population,O+,A+,B+,AB+,O-,A-,B-,AB-,Continent,Total_Positive,Total_Negative,Positive_Minus_Negative
8,Bangladesh,168697184,29.21,26.30,33.12,9.59,0.530000,0.480000,0.600000,0.17000,AS,98.22,1.780000,96.440000
14,Brazil,220051512,36.00,34.00,8.00,2.50,9.000000,8.000000,2.000000,0.50000,SA,80.50,19.500000,61.000000
27,Democratic Republic of the Congo,115403027,59.50,21.30,15.20,2.40,1.000000,0.300000,0.200000,0.10000,AF,98.40,1.600000,96.800000
31,Egypt,111247248,36.44,33.94,20.96,8.65,4.126349,3.362619,1.360397,0.47371,AF,99.99,9.323075,90.666925
34,Ethiopia,118550298,39.00,28.00,21.00,5.00,3.000000,2.000000,1.000000,1.00000,AF,93.00,7.000000,86.000000
37,France,68374591,36.50,38.20,7.70,2.50,6.500000,6.800000,1.400000,0.40000,EU,84.90,15.100000,69.800000
40,Germany,84119100,35.00,37.00,9.00,4.00,6.000000,6.000000,2.000000,1.00000,EU,85.00,15.000000,70.000000
48,India,1409128296,32.53,21.80,32.10,7.70,2.030000,1.360000,2.000000,0.48000,AS,94.13,5.870000,88.260000
49,Indonesia,281562465,36.82,25.87,28.85,7.96,0.180000,0.130000,0.150000,0.04000,AS,99.50,0.500000,99.000000
50,Iran,88386937,36.50,27.00,22.20,4.00,5.000000,2.000000,2.500000,0.80000,AS,89.70,10.300000,79.400000
54,Italy,60964931,39.00,36.00,7.50,2.50,7.000000,6.000000,1.500000,0.50000,EU,85.00,15.000000,70.000000
57,Japan,123201945,29.90,39.80,19.90,9.90,0.150000,0.200000,0.100000,0.05000,AS,99.50,0.500000,99.000000
60,Kenya,58246378,45.60,25.20,21.28,4.20,1.800000,1.000000,0.900000,0.02000,AF,96.28,3.720000,92.560000
73,Mexico,130739927,59.09,26.23,8.53,1.73,2.730000,1.210000,0.400000,0.08000,AS,95.58,4.420000,91.160000
77,Myanmar,57527139,35.70,23.80,32.70,6.95,0.300000,0.200000,0.300000,0.05000,AS,99.15,0.850000,98.300000
83,Nigeria,236747130,50.23,21.61,19.59,3.47,2.700000,1.160000,1.050000,0.19000,AF,94.90,5.100000,89.800000
88,Pakistan,252363571,30.04,21.53,30.24,8.83,3.100000,2.220000,3.130000,0.91000,AS,90.64,9.360000,81.280000
92,Philippines,118277063,45.90,22.90,24.90,5.97,0.100000,0.100000,0.100000,0.03000,AS,99.67,0.330000,99.340000
95,People's Republic of China,1416043270,34.00,27.60,28.90,8.40,0.400000,0.250000,0.200000,0.15000,AS,98.90,1.000000,97.900000
97,Russia,140820810,36.00,31.00,19.00,2.10,6.000000,4.000000,1.000000,0.90000,EU,88.10,11.900000,76.200000
104,South Africa,60442647,39.00,32.00,12.00,3.00,6.000000,5.000000,2.000000,1.00000,AF,86.00,14.000000,72.000000
105,South Korea,52081799,29.00,32.00,31.00,8.00,0.190000,0.100000,0.100000,0.01000,AS,100.00,0.400000,99.600000
108,Sudan,50467278,48.00,27.70,15.20,2.30,3.500000,1.800000,0.800000,0.20000,AF,93.20,6.300000,86.900000
113,Thailand,69920998,40.80,16.90,36.80,4.97,0.200000,0.100000,0.200000,0.03000,AS,99.47,0.530000,98.940000
115,Turkey,84119531,29.40,38.30,13.20,6.40,4.400000,5.500000,2.100000,0.70000,AS,87.30,12.700000,74.600000
120,United States,341963408,37.40,35.70,8.50,3.40,6.600000,6.300000,1.500000,0.60000,AS,85.00,15.000000,70.000000
123,Vietnam,105758975,41.70,20.90,30.80,4.98,0.300000,0.100000,0.200000,0.02000,AS,98.38,0.620000,97.760000

In [138]:
top_5_population = df.sort_values('Population', ascending= False).head(5)
top_5_population[['Country', 'Population']]

                        Country  Population
126                       World  8057236243
95   People's Republic of China  1416043270
48                        India  1409128296
120               United States   341963408
49                    Indonesia   281562465

In [140]:
df.groupby('Continent')['Population'].sum().idxmax()

'AS'

In [142]:
df.groupby('Continent')['Country'].count().idxmax()

'AS'

In [144]:
df.loc[df['Total_Positive'].idxmax(), ['Country', 'Total_Positive']]

Country           Nepal
Total_Positive    101.2
Name: 79, dtype: object

In [146]:
df.loc[df['Total_Negative'].idxmin(), ['Country', 'Total_Negative']]

Country           Bhutan
Total_Negative      0.15
Name: 11, dtype: object

In [151]:
top_5_positive = df.sort_values('Total_Positive', ascending=False).head(5)
top_5_positive[['Country', 'Total_Positive']]

         Country  Total_Positive
79         Nepal          101.20
105  South Korea          100.00
45     Hong Kong          100.00
31         Egypt           99.99
11        Bhutan           99.87

In [152]:
top_5_negative = df.sort_values('Total_Negative', ascending = False).head(5)
top_5_negative[['Country', 'Total_Negative']]

            Country  Total_Negative
75         Mongolia           23.31
126           World           23.21
119  United Kingdom           20.00
14           Brazil           19.50
106           Spain           18.50

In [153]:
high_pop_positive = df[
    (df['Population'] > 50000000) &
    (df['Total_Positive'] > 80)
]

high_pop_positive[['Country', 'Population', 'Total_Positive']]

                              Country  Population  Total_Positive
8                          Bangladesh   168697184           98.22
14                             Brazil   220051512           80.50
27   Democratic Republic of the Congo   115403027           98.40
31                              Egypt   111247248           99.99
34                           Ethiopia   118550298           93.00
37                             France    68374591           84.90
40                            Germany    84119100           85.00
48                              India  1409128296           94.13
49                          Indonesia   281562465           99.50
50                               Iran    88386937           89.70
54                              Italy    60964931           85.00
57                              Japan   123201945           99.50
60                              Kenya    58246378           96.28
73                             Mexico   130739927           95.58
77                            Myanmar    57527139           99.15
83                            Nigeria   236747130           94.90
88                           Pakistan   252363571           90.64
92                        Philippines   118277063           99.67
95         People's Republic of China  1416043270           98.90
97                             Russia   140820810           88.10
104                      South Africa    60442647           86.00
105                       South Korea    52081799          100.00
108                             Sudan    50467278           93.20
113                          Thailand    69920998           99.47
115                            Turkey    84119531           87.30
120                     United States   341963408           85.00
123                           Vietnam   105758975           98.38

In [154]:
df.groupby('Continent')['O+'].mean().idxmax()

'SA'

In [155]:
df.groupby('Continent')['Total_Positive'].mean().idxmax()

'AS'

In [156]:
df.groupby('Continent')['Total_Positive'].mean()

Continent
AF    93.275217
AS    93.556346
EU    84.725641
OC    91.550000
SA    90.944444
Name: Total_Positive, dtype: float64

In [157]:
df.groupby('Continent')['Total_Negative'].mean().idxmax()

'EU'

In [161]:
df['Continent'].value_counts().idxmax()

'AS'

In [162]:
df.loc[df['Population'].idxmax(), ['Country', 'Population']]

Country            World
Population    8057236243
Name: 126, dtype: object

In [163]:
df.loc[df['Population'].idxmin(), ['Country', 'Population']]

Country       Liechtenstein
Population            40272
Name: 65, dtype: object

In [164]:
df.shape

(127, 14)

In [165]:
df.columns

Index(['Country', 'Population', 'O+', 'A+', 'B+', 'AB+', 'O-', 'A-', 'B-',
       'AB-', 'Continent', 'Total_Positive', 'Total_Negative',
       'Positive_Minus_Negative'],
      dtype='str')